/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TourismeMedicalRouteImport } from './routes/tourisme-medical'
import { Route as MauritanieRouteImport } from './routes/mauritanie'
import { Route as EtudesRouteImport } from './routes/etudes'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as IndexRouteImport } from './routes/index'

const TourismeMedicalRoute = TourismeMedicalRouteImport.update({
  id: '/tourisme-medical',
  path: '/tourisme-medical',
  getParentRoute: () => rootRouteImport,
} as any)
const MauritanieRoute = MauritanieRouteImport.update({
  id: '/mauritanie',
  path: '/mauritanie',
  getParentRoute: () => rootRouteImport,
} as any)
const EtudesRoute = EtudesRouteImport.update({
  id: '/etudes',
  path: '/etudes',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/etudes': typeof EtudesRoute
  '/mauritanie': typeof MauritanieRoute
  '/tourisme-medical': typeof TourismeMedicalRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/etudes': typeof EtudesRoute
  '/mauritanie': typeof MauritanieRoute
  '/tourisme-medical': typeof TourismeMedicalRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/etudes': typeof EtudesRoute
  '/mauritanie': typeof MauritanieRoute
  '/tourisme-medical': typeof TourismeMedicalRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/contact' | '/etudes' | '/mauritanie' | '/tourisme-medical'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/contact' | '/etudes' | '/mauritanie' | '/tourisme-medical'
  id:
    | '__root__'
    | '/'
    | '/contact'
    | '/etudes'
    | '/mauritanie'
    | '/tourisme-medical'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactRoute: typeof ContactRoute
  EtudesRoute: typeof EtudesRoute
  MauritanieRoute: typeof MauritanieRoute
  TourismeMedicalRoute: typeof TourismeMedicalRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tourisme-medical': {
      id: '/tourisme-medical'
      path: '/tourisme-medical'
      fullPath: '/tourisme-medical'
      preLoaderRoute: typeof TourismeMedicalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mauritanie': {
      id: '/mauritanie'
      path: '/mauritanie'
      fullPath: '/mauritanie'
      preLoaderRoute: typeof MauritanieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/etudes': {
      id: '/etudes'
      path: '/etudes'
      fullPath: '/etudes'
      preLoaderRoute: typeof EtudesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactRoute: ContactRoute,
  EtudesRoute: EtudesRoute,
  MauritanieRoute: MauritanieRoute,
  TourismeMedicalRoute: TourismeMedicalRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
